# konfiguracja pluginu "kociak-portfel" wykonanego przez piotrkociakx
# podszywanie się pod autora oraz usuwanie tej linijki jest ZABRONIONE

ItemShopGui:
  options:
    title: "&0Sklep z rangami"
    slots: 27
    background: "BLACK_STAINED_GLASS_PANE" # Materiał tła GUI
  gui:
    11: # slot
      material: GOLD_BLOCK # materiał
      count: 1 # liczba przedmiotow
      enchanted: true # czy przedmiot ma mieć połysk
      name: "&eRanga &6VIP &eNa 30 dni" # nazwa przedmiotu
      lore: # opis
        - "&cKoszt 5 pln"
        - "&e/vip"
      closegui: true # czy gui ma zostac zamkniete po zakupie
      cost: 5 # koszt zakupu
      commands: # akcje wykonywane po zakupie
        - "luckperms user {player} addtemp vip 30d" # komenda wywoływana przez konsole ze zmienną {player}
    15:
      material: EMERALD_BLOCK
      count: 1
      enchanted: true
      name: "&aRanga &2Emerald &ana 30 dni!"
      lore:
        - "&cKoszt 20 pln"
        - "&a/emerald"
      closegui: true
      cost: 20
      commands:
        - "luckperms user {player} addtemp emerald 30d"

    # dodaj więcej rzeczy do gui w ten sam sposob jak jest wcześniej pokazane

messages:
  balance: "&aMasz teraz {balance} pln" # zmienne {balance}
commands:
  enabled:
    adminportfel: true
    itemshop: true
    portfel: true
