name: kociak-portfel
description: "plugin na portfel na 1.8.8+"
version: 1.0
main: pl.piotrkociakx.template.Main
api-version: '1.13'
load: STARTUP
authors: [piotrkociakx]
website: https:///www.piotrkociakx.pl
loadbefore:
  - PlaceholderAPI
depend:
  - PlaceholderAPI
softdepend:
  - PlaceholderAPI
commands:
  adminportfel:
    aliases:
      - aportfel
      - kociakportfeladmin
      - portfeladmin
  portfel:
    aliases:
      - stankonta
      - pieniadze
  itemshop:
    aliases:
      - rangi
      - zakuprang
      - uslugi
permissions:
  kociakportfel.admin:
    default: false
